version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: person_db_container
    environment:
      POSTGRES_DB: person_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  # Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # External address
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"  # External port

  # Kafka UI Service
  kafka-ui:
    container_name: pms-kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8085:8080"  # External port for Kafka UI
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092  # Internal address for Kafka UI to connect to Kafka